const diceImages = {
    4: {
        1: require('../assets/d4-1.png'),
        2: require('../assets/d4-2.png'),
        3: require('../assets/d4-3.png'),
        4: require('../assets/d4-4.png')
    },
    6: {
        1: require('../assets/d6-1.png'),
        2: require('../assets/d6-2.png'),
        3: require('../assets/d6-3.png'),
        4: require('../assets/d6-4.png'),
        5: require('../assets/d6-5.png'),
        6: require('../assets/d6-6.png'),
    },
    8: {
        1: require('../assets/d8-1.png'),
        2: require('../assets/d8-2.png'),
        3: require('../assets/d8-3.png'),
        4: require('../assets/d8-4.png'),
        5: require('../assets/d8-5.png'),
        6: require('../assets/d8-6.png'),
        7: require('../assets/d8-7.png'),
        8: require('../assets/d8-8.png'),
    },
    12: {
        1: require('../assets/d12-1.png'),
        2: require('../assets/d12-2.png'),
        3: require('../assets/d12-3.png'),
        4: require('../assets/d12-4.png'),
        5: require('../assets/d12-5.png'),
        6: require('../assets/d12-6.png'),
        7: require('../assets/d12-7.png'),
        8: require('../assets/d12-8.png'),
        9: require('../assets/d12-9.png'),
        10: require('../assets/d12-10.png'),
        11: require('../assets/d12-11.png'),
        12: require('../assets/d12-12.png'),
    },
    20: {
        1: require('../assets/d20-1.png'),
        2: require('../assets/d20-2.png'),
        3: require('../assets/d20-3.png'),
        4: require('../assets/d20-4.png'),
        5: require('../assets/d20-5.png'),
        6: require('../assets/d20-6.png'),
        7: require('../assets/d20-7.png'),
        8: require('../assets/d20-8.png'),
        9: require('../assets/d20-9.png'),
        10: require('../assets/d20-10.png'),
        11: require('../assets/d20-11.png'),
        12: require('../assets/d20-12.png'),
        13: require('../assets/d20-13.png'),
        14: require('../assets/d20-14.png'),
        15: require('../assets/d20-15.png'),
        16: require('../assets/d20-16.png'),
        17: require('../assets/d20-17.png'),
        18: require('../assets/d20-18.png'),
        19: require('../assets/d20-19.png'),
        20: require('../assets/d20-20.png'),
    }
};

export default diceImages;